site_name: CLI for Microsoft 365
nav:
  - Home: 'index.md'
theme:
  name: 'material'
  palette:
    primary: 'red'
  logo: 'images/pnp-cli-microsoft365-white.svg'
  feature:
    tabs: true
google_analytics:
  - 'UA-110480857-10'
  - 'auto'
extra_css:
  - 'css/styles.css'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.snippets
  - def_list
extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/m365pnp'
    - type: 'youtube'
      link: 'http://aka.ms/sppnp-videos'
    - type: 'link'
      link: 'https://aka.ms/sppnp'
repo_url: http://github.com/pnp/cli-microsoft365
edit_uri: blob/master/docs/docs